export const products = [
  {
    id: '1',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 1',
    productName: 'Lamtorin fungisetasdadasdas 1 LT',
    price: '₺100',
  },
  {
    id: '1',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 1',
    productName: 'Ürün Adı 1',
    price: '₺100',
  },
  {
    id: '1',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 1',
    productName: 'Ürün Adı 1',
    price: '₺100',
  },
  {
    id: '1',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 1',
    productName: 'Ürün Adı 1',
    price: '₺100',
  },
  {
    id: '1',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 1',
    productName: 'Ürün Adı 1',
    price: '₺100',
  },
  {
    id: '2',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 2',
    productName: 'Ürün Adı 2',
    price: '₺200',
  },
  {
    id: '3',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 3',
    productName: 'Ürün Adı 3',
    price: '₺300',
  },
  {
    id: '4',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 4',
    productName: 'Ürün Adı 4',
    price: '₺400',
  },
  {
    id: '5',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 5',
    productName: 'Ürün Adı 5',
    price: '₺500',
  },
  {
    id: '6',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 6',
    productName: 'Ürün Adı 6',
    price: '₺600',
  },
  {
    id: '4',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 4',
    productName: 'Ürün Adı 4',
    price: '₺400',
  },
  {
    id: '5',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 5',
    productName: 'Ürün Adı 5',
    price: '₺500',
  },
];
export const messages = [
  {
    id: 1,
    statusColor: '#FF6A00',
    imageUrl: 'https://via.placeholder.com/50',
    productName: 'Ürün Adı',
    seller: 'A Ziraat Bayi',
    description:
      'Lorem Ipsum is simply dummy text of the printing and type ...',
    date: '28 Ekim 2024',
  },
  {
    id: 2,
    statusColor: '#FF6A00',
    imageUrl: 'https://via.placeholder.com/50',
    productName: 'Ürün Adı',
    seller: 'A Ziraat Bayi',
    description:
      'Lorem Ipsum is simply dummy text of the printing and type ...',
    date: '28 Ekim 2024',
  },
  {
    id: 3,
    statusColor: '#FF6A00',
    imageUrl: 'https://via.placeholder.com/50',
    productName: 'Ürün Adı',
    seller: 'A Ziraat Bayi',
    description:
      'Lorem Ipsum is simply dummy text of the printing and type ...',
    date: '28 Ekim 2024',
  },
  {
    id: 4,
    statusColor: '#999999',
    imageUrl: 'https://via.placeholder.com/50',
    productName: 'Ürün Adı',
    seller: 'A Ziraat Bayi',
    description:
      'Lorem Ipsum is simply dummy text of the printing and type ...',
    date: '28 Ekim 2024',
  },
];
