export const products = [
  {
    id: '1',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 1',
    productName: 'Lamtorin fungisetasdadasdas 1 LT',
    price: '₺100',
  },
  {
    id: '1',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 1',
    productName: 'Ürün Adı 1',
    price: '₺100',
  },
  {
    id: '1',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 1',
    productName: 'Ürün Adı 1',
    price: '₺100',
  },
  {
    id: '1',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 1',
    productName: 'Ürün Adı 1',
    price: '₺100',
  },
  {
    id: '1',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 1',
    productName: 'Ürün Adı 1',
    price: '₺100',
  },
  {
    id: '2',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 2',
    productName: 'Ürün Adı 2',
    price: '₺200',
  },
  {
    id: '3',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 3',
    productName: 'Ürün Adı 3',
    price: '₺300',
  },
  {
    id: '4',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 4',
    productName: 'Ürün Adı 4',
    price: '₺400',
  },
  {
    id: '5',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 5',
    productName: 'Ürün Adı 5',
    price: '₺500',
  },
  {
    id: '6',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 6',
    productName: 'Ürün Adı 6',
    price: '₺600',
  },
  {
    id: '4',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 4',
    productName: 'Ürün Adı 4',
    price: '₺400',
  },
  {
    id: '5',
    image: 'https://via.placeholder.com/150',
    categoryName: 'Kategori Adı 5',
    productName: 'Ürün Adı 5',
    price: '₺500',
  },
];
